version: "3.9"

services:
  backend1:
    build: ./RUSHLESS-BE-MASTER
    container_name: RUSHLESS-BE-MASTER
    ports:
      - "5000:5000"
    volumes:
      - ./RUSHLESS-BE-MASTER:/app
    environment:
      - NODE_ENV=production

  backend2:
    build: ./RUSHLESS-BE-EXAM
    container_name: RUSHLESS-BE-EXAM
    ports:
      - "4040:4040"
    volumes:
      - ./RUSHLESS-BE-EXAM:/app
    environment:
      - NODE_ENV=production

  frontend:
    build: ./RUSHLESS-FE
    container_name: RUSHLESS-FE
    ports:
      - "80:80"
    volumes:
      - ./RUSHLESS-FE:/app

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=60

