version: "3.9"

services:
  # ---------- Backend Master ----------
  rushless-be-master:
    build:
      context: ./RUSHLESS-BE-MASTER
      dockerfile: Dockerfile
    container_name: rushless-be-master
    ports:
      - "5001:5001"
    restart: unless-stopped
    environment:
      NODE_ENV: production

  # ---------- Backend Exam ----------
  rushless-be-exam:
    build:
      context: ./RUSHLESS-BE-EXAM
      dockerfile: Dockerfile
    container_name: rushless-be-exam
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      NODE_ENV: production

  # ---------- Frontend React ----------
  rushless-fe:
    build:
      context: ./RUSHLESS-FE
      dockerfile: Dockerfile
    container_name: rushless-fe
    ports:
      - "3000:80"
    restart: unless-stopped
